baseURL = "https://example.com"
languageCode = "en-us"
title = "Cactus theme example"
theme = "cactus"
copyright = "You" # cactus will use title if copyright is not set
disqusShortname = "example" # Used when comments is enabled. Cactus will use site title if not set
# googleAnalytics = "UA-1234-5"


# summaryLength = 2

# Main menu which appears below site header.
[[menu.main]]
name = "Home"
url = "/"
weight = 1

[[menu.main]]
name = "Writings"
url = "/posts"
weight = 2

[[menu.main]]
name = "Tags"
url = "/tags"
weight = 3

[[menu.main]]
name = "About"
url = "/about"
weight = 4

[markup]
  [markup.tableOfContents]
    endLevel = 4
    ordered = false
    startLevel = 2

[params]

  colortheme = "white" # dark, light, white, or classic
  rss = true # generate rss feed. default value is false
  googleAnalyticsAsync = true # use asynchronous tracking. Synchronous tracking by default

  # Home page settings
  description = "Hugo is a general-purpose website framework. Technically speaking, Hugo is a static site generator. Unlike systems that dynamically build a page with each visitor request, Hugo builds pages when you create or update your content. Since websites are viewed far more often than they are edited, Hugo is designed to provide an optimal viewing experience for your websiteâ€™s end users and an ideal writing experience for website authors."
  mainSection = "posts" # your main section
  showAllPostsOnHomePage = false # default
  postsOnHomePage = 5 # this option will be ignored if showAllPostsOnHomePage is set to true
  tagsOverview = true # show tags overview by default.
  showProjectsList = true # show projects list by default (if projects data file exists).
  projectsUrl = "https://github.com/gohugoio" # title link for projects list

  # https://gohugo.io/functions/format/#hugo-date-and-time-templating-reference
  dateFormat = "2006-01-02" # default

  # Post page settings
  show_updated = false # default

  [params.comments]
    enabled = false # default
    engine = "disqus" # more supported engines will be added.

  # the value of name should be an valid font awesome icon name (brands type)
  # https://fontawesome.com/icons?d=gallery&s=brands
  [[params.social]]
    name = "github"
    link = "https://github.com/gohugoio"
  [[params.social]]
    name = "linkedin"
    link = "https://www.linkedin.com/company/github/"
  [[params.social]]
    name = "email"
    link = "example@example.com"  # no need for "mailto:" in the head
